language: rust
sudo: false
matrix:
  include:
  - rust: stable
  - rust: beta
  - rust: nightly
    env: FEATURES=futures-spawn
script:
- cargo build --verbose --features "$FEATURES"
- cargo test --verbose --features "$FEATURES"
